### PR TITLE
fix version of android flutter dependencies

### PR DESCRIPTION
**Pull request by 4BooM04**

### CODE REVIEW

**Comment by 4BooM04** [comment]
small fix for the issues with gradle and dependencies configuration during build time

**Review by Sarbjyotsingh — APPROVED** [review]

**Review by rutkayb — APPROVED** [review]

**Comment by hudson-pierce** [comment]
run tests

**Comment by hudson-pierce** [comment]
run tests

**Comment by hudson-pierce** [comment]
run tests

**Comment by hudson-pierce** [comment]
run tests

**Comment by hudson-pierce** [comment]
run tests

**Comment by hudson-pierce** [comment]
run tests

**Comment by hudson-pierce** [comment]
run tests

**Pull request merged**
